### ISSUE TITLE
Troubles with using env variables or secrets

### ISSUE THREAD

**Issue by markrity** [joshuaavalon/flyway-action#3]
```
      - uses: joshuaavalon/flyway-action@v1
        with:
          url: jdbc:mysql://$MYSQL_HOST:3306/database
          user: $MYSQL_USER
          password: $MYSQL_PW
          locations: filesystem:./conf/db_migrations/sql
```
I set envs like this:
```
env:
  MYSQL_HOST: ${{ secrets.MYSQL_STAGING_HOST }}
  MYSQL_USER: ${{ secrets.MYSQL_STAGING_USER }}
  MYSQL_PW: ${{ secrets.MYSQL_STAGING_PW}}
```
I also tried to set em like this:
```
          url: jdbc:mysql://${{ secrets.MYSQL_STAGING_HOST }}:3306/database
          user: ${{ secrets.MYSQL_STAGING_USER }}
          password: ${{ secrets.MYSQL_STAGING_PW }}
```

Both ways resulted with the same error, am I missing something? 

ERROR: Unable to obtain connection from database (jdbc:mysql://$MYSQL_HOST:3306/database) for user '$MYSQL_USER': Communications link failure
```
